### ISSUE TITLE
Create-Targed-DB MySQL Version Update

### ISSUE THREAD

**Issue by maroskukan** [aws-samples/application-migration-with-aws-workshop#35]
Hi there!

I recently attempted this lab at an AWS hosted event, and noticed that MySQL version running in source environment 
is not 5.7.22, but 5.7.33. Therefore it would be good to updated the Create-Target-DB documents.

**Comment by lechmigdal** [comment]
Fixed [with this commit](https://github.com/aws-samples/application-migration-with-aws-workshop/commit/4cde79f255adc8433f4793d15e722be48749916a)
