### ISSUE TITLE
DMS Instance Class

### ISSUE THREAD

**Issue by maroskukan** [aws-samples/application-migration-with-aws-workshop#36]
Hi there!

I recently attempted this lab at an AWS hosted event, and noticed that referenced DMS Instance class **dms.t2.medium** 
is no longer available for selection without enabling _Include previous-generation instance classes selected_. It should be changed to **dms.t3.medium** or this checkbox should be marked in documentation. It would be good to updated the create-replication-instance documents.

**Comment by lechmigdal** [comment]
thank you, fixed with https://github.com/aws-samples/application-migration-with-aws-workshop/commit/170e34be82ea9717d4619891fd916a6cc1c634fe
